// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8TxCb-2yaGULX5Fqc8N4zdMH4iTiu-4',
    appId: '1:956887929807:web:2766b67675ee98998278ba',
    messagingSenderId: '956887929807',
    projectId: 'flutter-chat-app-auth',
    authDomain: 'flutter-chat-app-auth.firebaseapp.com',
    storageBucket: 'flutter-chat-app-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqWiCP7lFWuwOYYVV_YNjHgaYh8-93ME',
    appId: '1:956887929807:android:d4f1aed8165f91ec8278ba',
    messagingSenderId: '956887929807',
    projectId: 'flutter-chat-app-auth',
    storageBucket: 'flutter-chat-app-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqMOe67xcnd-WoWqAt8vuIw9micledWiY',
    appId: '1:956887929807:ios:0a6c76aad1eb184c8278ba',
    messagingSenderId: '956887929807',
    projectId: 'flutter-chat-app-auth',
    storageBucket: 'flutter-chat-app-auth.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqMOe67xcnd-WoWqAt8vuIw9micledWiY',
    appId: '1:956887929807:ios:a53af1e81a0ae5748278ba',
    messagingSenderId: '956887929807',
    projectId: 'flutter-chat-app-auth',
    storageBucket: 'flutter-chat-app-auth.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
